[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
fonts = "1.9.5"
ksp = "2.3.3"
hilt = "2.57.2"
hiltWorker = "1.3.0"
hiltNavigationCompose = "1.3.0"
media3 = "1.8.0"
transcoder = "1.1.0"
ktlint = "14.0.1"
ktlint-compose = "0.4.28"
serialization = "2.2.0"
json = "1.9.0"
resampler = "0.3"
room = "2.8.4"
nav3Core = "1.0.0"
lottie = "6.6.6"
worker = "2.11.0"
splashscreen = "1.0.0"
permission = "0.37.3"
coil = "3.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-hilt-worker = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorker" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltWorker" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "fonts" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose"}
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-uicompose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "media3" }
android-transcoder = { group = "io.github.vinnih-1", name = "android-transcoder", version.ref = "transcoder" }
android-resampler = { group = "io.github.nailik", name = "androidresampler", version.ref = "resampler" }
ktlint-compose = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "ktlint-compose" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "json" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
worker-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "worker" }
google-accompanist-permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "permission" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp"  }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }